In [1]:
import numpy as np

In [2]:
# One dimensional array
od_array= np.array([1,2,3,4,5])
type(od_array)

numpy.ndarray

In [3]:
od_array.shape

(5,)

In [4]:
print(od_array[4])

5


In [5]:
# Two dimensional array
td_array= np.array([[1,2,3,4,5], [11,12,13,14,15]])
print(td_array)

[[ 1  2  3  4  5]
 [11 12 13 14 15]]


In [6]:
td_array.shape

(2, 5)

In [7]:
print(td_array[1,4])

15


In [8]:
zeros_matrix= np.zeros((3,3))
print(zeros_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
ones_matrix= np.ones((3,3))
print(ones_matrix)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
# Filled with custom value
custom= np.full((3,3), 25)
print(custom)

[[25 25 25]
 [25 25 25]
 [25 25 25]]


In [11]:
# 3*3 matrix with diagonal 1s and other 0s
identity_matrix= np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
array= np.array([[10,11,12], [20,21,22], [30,31,32]])
print(array)

[[10 11 12]
 [20 21 22]
 [30 31 32]]


In [13]:
# [:2]: Selects the first two rows (rows at index 0 and 1).
# [1:3]: Selects columns 1 and 2 (columns at index 1 and 2).
slice= array[:2, 1:3]
print(slice)

[[11 12]
 [21 22]]


In [14]:
array= np.array([[10,11,12], [20,21,22], [30,31,32]])
check= (array %2 ==0)
check

array([[ True, False,  True],
       [ True, False,  True],
       [ True, False,  True]])

In [15]:
array= np.array([10.1, 11.7, 12.5])
print(array.dtype)
print(array)

print()

array= np.array([10.1, 11.7, 12.5], dtype=np.int64)
print(array.dtype)
print(array)

float64
[10.1 11.7 12.5]

int64
[10 11 12]


In [16]:

x = np.array([[111,112],[121,122]], dtype=np.float64)
y = np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)

# Addition by onventional way
print(x + y)
print()

# Addition using nummpy silimar for sub, mul, div, square root(sqrt())
print(np.add(x, y))

[[322.1 324.1]
 [342.1 344.1]]

[[322.1 324.1]
 [342.1 344.1]]


In [17]:
# Exponent (e ** x)
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


In [18]:
array = 10* np.random.rand(2,5)
print(array)

[[4.37553753 3.11134871 7.25421252 6.14707088 5.72434874]
 [1.4353029  3.46763346 5.64589743 1.22382307 8.35520664]]


In [19]:
print(array.mean())

4.67403818850237


In [20]:
# Compute the means by row
print(array.mean(axis = 1))

[5.32250368 4.0255727 ]


In [21]:
# Compute the means by column
print(array.mean(axis=0))

[2.90542022 3.28949108 6.45005497 3.68544698 7.03977769]


In [22]:
# Sum of all elements
print(array.sum())

46.740381885023695


In [23]:
# Compute the medians
print(np.median(array, axis = 1))

[5.72434874 3.46763346]


In [24]:
# Finding unique elements
array = np.array([1,2,1,4,2,1,4,2])
print(np.unique(array))

[1 2 4]


In [25]:
s1 = np.array(['desk','chair','bulb'])
s2 = np.array(['lamp','bulb','chair'])
print(s1, s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [26]:
print( np.intersect1d(s1, s2) ) 

['bulb' 'chair']


In [27]:
print( np.union1d(s1, s2) )

['bulb' 'chair' 'desk' 'lamp']


In [28]:
# Set difference between two sets (elements in s1 that are not in s2)
print( np.setdiff1d(s1, s2) )

['desk']


In [29]:
x = np.array([ 7.25, 11.11])

In [30]:
np.save("array.npy", x)

In [31]:
np.load("array.npy")

array([ 7.25, 11.11])

In [32]:
np.savetxt('array.txt', X=x, delimiter=',')

In [33]:
np.loadtxt('array.txt', delimiter=',')

array([ 7.25, 11.11])

In [34]:
x2d = np.array([[1,1],[1,1]])
y2d = np.array([[2,2],[2,2]])

print(np.dot(x2d, y2d))

[[4 4]
 [4 4]]


In [35]:
df1= np.random.randint(low=0, high=9, size=(4,4))
print(df1)

print()

df2=np.random.randint(low=0, high=9, size=(4,4))
print(df2)

[[7 4 1 4]
 [1 6 3 1]
 [4 1 8 7]
 [8 3 3 6]]

[[8 7 5 3]
 [2 6 1 0]
 [4 4 1 1]
 [7 1 5 1]]


In [36]:
# Merging dataset by stacking(vertical)
np.vstack((df1, df2))

array([[7, 4, 1, 4],
       [1, 6, 3, 1],
       [4, 1, 8, 7],
       [8, 3, 3, 6],
       [8, 7, 5, 3],
       [2, 6, 1, 0],
       [4, 4, 1, 1],
       [7, 1, 5, 1]], dtype=int32)

In [37]:
# Merging dataset by stacking(horizontal)
np.hstack((df1, df2))

array([[7, 4, 1, 4, 8, 7, 5, 3],
       [1, 6, 3, 1, 2, 6, 1, 0],
       [4, 1, 8, 7, 4, 4, 1, 1],
       [8, 3, 3, 6, 7, 1, 5, 1]], dtype=int32)

In [38]:
np.concatenate([df1, df2], axis = 0)

array([[7, 4, 1, 4],
       [1, 6, 3, 1],
       [4, 1, 8, 7],
       [8, 3, 3, 6],
       [8, 7, 5, 3],
       [2, 6, 1, 0],
       [4, 4, 1, 1],
       [7, 1, 5, 1]], dtype=int32)

In [39]:
np.concatenate([df1, df2.T], axis = 1)

array([[7, 4, 1, 4, 8, 2, 4, 7],
       [1, 6, 3, 1, 7, 6, 4, 1],
       [4, 1, 8, 7, 5, 1, 1, 5],
       [8, 3, 3, 6, 3, 0, 1, 1]], dtype=int32)